#!/bin/sh

set -e

[ -z "$DEBUG" ] || set -x

echo "===> Generate build...\n"

CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o build/c4-active

echo "\n===> Generate image...\n"

docker build --no-cache -t c4-active .

echo "\n===> Docker tag...\n"

docker tag c4-active fernandocagale/c4-active

echo "\n===> Docker push...\n"

docker push fernandocagale/c4-active

echo "\n===> Kubectl apply V1...\n"

kubectl apply -f kubernetes/c4-active-v1-deployment.yml -n c4

echo "\n===> Kubectl apply V2...\n"

kubectl apply -f kubernetes/c4-active-v2-deployment.yml -n c4

echo "\n===> Kubectl pods...\n"

kubectl get pods -n c4